name: 'build, test'
description: 'composite actions'
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
      - name: Build with Gradle
        run: ./gradlew build
        shell: bash
      - name: Run Test Coverage
        run: ./gradlew jacocoTestReport
      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}" 
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
        shell: bash
